The-Fruity-Mixologist-Back-End-/TheFruityMixologist/Entities/gifCart.cs
using TheFruityMixologist.Utilities.Enum;

namespace TheFruityMixologist.Entities
{
    public class gifCart:BaseEntity
    {
        public User User { get; set; }
        public string RecipientName { get; set; }
        public string Message { get; set; }
        public OrderStatus status { get; set; }
        public int PriceOptionId { get; set; }
        public int GiftCartColorId { get; set; }
        public PriceOption PriceOption { get; set; }
        public giftCartColor GiftCartColor { get; set; }
    }
}

The-Fruity-Mixologist-Back-End-/TheFruityMixologist/Controllers/GifcartController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using TheFruityMixologist.DAL;
using TheFruityMixologist.Entities;
using TheFruityMixologist.ViewModels;
using TheFruityMixologist.ViewModels.gifCard;
using TheFruityMixologist.ViewModels.Order;

namespace TheFruityMixologist.Controllers
{
    public class GifcartController:Controller
    {
        private readonly MixologistDbContext _context;
        private readonly UserManager<User> _userManager;
        private readonly SignInManager<User> _signInManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly IWebHostEnvironment _env;


        public GifcartController(MixologistDbContext context,UserManager<User> userManager, SignInManager<User> signInManager, RoleManager<IdentityRole> roleManager, IWebHostEnvironment env)
        {
            _context = context;
            _userManager = userManager;
            _signInManager = signInManager;
            _roleManager = roleManager;
            _env = env;
        }

        public IActionResult Index()
            {
                List<User> users = _context.Users.ToList();

                ViewBag.UserList = new SelectList(users, "Id", "UserName");

                List<gifCart> gifCarts = _context.GifCarts.Include(g => g.GiftCartColor)
                                                 .Include(g => g.PriceOption)
                                                 .ToList();

                gifCartVM VM = new()
                {
                    PriceOptionList =_context.priceOptions.ToList(),
                    GiftCartColors = _context.giftCartColors.ToList()
                };

                return View(VM);
            }


        [HttpPost]
        public async Task<IActionResult> GiftCard(gifCartVM model)
        {
            string message = model.Message;
            string selectedUserName = model.RecipientName;

            User user = await _userManager.FindByNameAsync(User.Identity.Name);
            if (user is null)
            {
                return RedirectToAction("Login", "Account");
            }
            User selectedUser = _context.Users.FirstOrDefault(u => u.Id == selectedUserName);

            gifCart gift = new ()
            {
                User = user,
                RecipientName = selectedUserName, 
                Message = model.Message,
                PriceOptionId = model.SelectedAmountId,
                GiftCartColorId = model.SelectedCardColorId,
                status = Utilities.Enum.OrderStatus.Default,
            };
            if(gift.Message is null || gift.RecipientName is null)
            {
                return BadRequest("Melumatlari tam doldurun!");
            }
            
            _context.GifCarts.Add(gift);
            _context.SaveChanges();

            return RedirectToAction("Index","Home");
        }

        public IActionResult Delete(int id)
        {
            if (id == 0)
            {
                return NotFound();
            }
            gifCart gifCart = _context.GifCarts.FirstOrDefault(x => x.Id == id);

            _context.GifCarts.Remove(gifCart);
            _context.SaveChanges();
            return RedirectToAction("Index", "home");
        }
    }




    }

The-Fruity-Mixologist-Back-End-/TheFruityMixologist/Views/Gifcart/Index.cshtml
    @model gifCartVM
@{
    ViewData["Title"] = "Index";
}
<main>
    <section id="DigitalGiftCarts">
        <div class="container" style="position: relative;">
            <div class="row">
                <div class="image"></div>
                <div class="text">
                    <div class="title">Digital Gift Cards</div>
                    <div class="desc">
                        Not sure which delicious cocktail to send? Send a gift card and
                        let them choose! Gift card orders are non-refundable.
                    </div>
                    <div class="buttons">
                        <button class="redeemingGiftCard" type="submit">
                            <a href="">Redeeming a Gift Card</a>
                        </button>
                        <button class="checkGiftCardBalance" type="submit">
                            Check Gift Card Balance
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section id="BuyGiftCard">
        <div class="container">
            <div class="row">
                <div class="title">By a gift card</div>
                <form asp-controller="Gifcart" asp-action="GiftCard" method="post">
                    <div class="chooseCard">
                        <div class="header">1. Choose your gift card</div>
                        <div class="row">
                          @foreach (var item in Model.GiftCartColors)
                            {
                                  <div class="col-lg-4">
                                <div class="image">
                                    <img class="blackcard"
                                         width="100%"
                                         src="~/assets/photos/GifCard/@item.ImagePath"
                                         alt="" />
                                        <input name="SelectedCardColorId" value="@item.Id"  type="checkbox" class="black_check d-none" />
                                </div>
                            </div>
                            }
                        </div>
                    </div>

                    <div class="choosePrice">
                        <div class="header">2. How much is it for?</div>
                        <ul class="choose">
                        
                            @foreach (var item in Model.PriceOptionList)
                            {
                                  <li>
                                <span class="choosePricee">$@item.Amount</span>
                                    <input name="SelectedAmountId" value="@item.Id" type="checkbox" class="chooseCheck d-none" />
                            </li>
                            }
                          
                        </ul>
                    </div>

                    <div class="enterInformation">
                        <div class="header">3. Enter the information</div>

                        <div class="recipientName">
                            <label asp-for="RecipientName">Recipient’s Name *</label><br />
                            @Html.DropDownList("RecipientName", ViewBag.UserList as SelectList, "Select", new { id = "RecipientNameA" })


                        </div>
                        <div class="Message">
                            <label asp-for="Message"> Message *</label> <br />
                            <textarea placeholder="Message (optinonal)"
                                     asp-for="Message"
                                      cols="30"
                                      rows="10"></textarea>
                        </div>
                        
                        <a href="#DigitalGiftCarts">
                            <button class="addCartBasket" type="submit"><span>Add to basket</span></button>
                        </a>
                    </div>
                </form>
            </div>
        </div>

    </section>
</main>
@section Scripts{
}