The-Fruity-Mixologist-Back-End-/TheFruityMixologist/Controllers/ShopController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TheFruityMixologist.DAL;
using TheFruityMixologist.Entities;
using TheFruityMixologist.Services.Interfaces;
using TheFruityMixologist.Utilities.Comparer;
using TheFruityMixologist.Utilities.Enum;

namespace TheFruityMixologist.Controllers
{
    public class ShopController:Controller
    {
        private readonly MixologistDbContext _context;
        private readonly UserManager<User> _userManager;
        private readonly IRecipeService _recipeService;
        private readonly IRatingService _ratingService;

        public ShopController(MixologistDbContext context, UserManager<User> userManager,IRecipeService recipeService,IRatingService ratingService)
        {
            _context = context;
            _userManager = userManager;
            _recipeService = recipeService;
            _ratingService = ratingService;
        }
        public async Task<IActionResult> Index(int page = 1)
        {
            if (page <= 0)
            {
                page = 1;
            }
            ViewBag.Recipes = await _recipeService.GetAllAsyncwithPaginated(page);
            ViewBag.Ratings = await _ratingService.GetAllAsync();
            var query = _context.Recipes.AsQueryable();
            var results = ViewBag.Recipes;
            ViewBag.SelectedPage = page;
            ViewBag.TotalPage = Math.Ceiling(query.Count() / 9m);
            return View(results);
        }
        public async Task<IActionResult> Detail(int id)
        {
            ViewBag.Ratings = await _ratingService.GetAllAsync();
            if (id == 0) return NotFound();
            IQueryable<Recipe> recipes = _context.Recipes.AsNoTracking().AsQueryable();
            Recipe? recipe = await _recipeService.GetFullDataByIdAsync(id);

            ViewBag.RelatedProduct = RelatedProducts(recipes, recipe, id);
            if (recipe == null) return NotFound();
            return View(recipe);
        }


        [HttpPost]
        public async Task<IActionResult> Sorts(string? sort)
        {
            ViewBag.Ratings = await _ratingService.GetAllAsync();

            IEnumerable<Recipe> recipes = await _recipeService.GetAllAsync();

            if (!string.IsNullOrEmpty(sort))
            {
                switch (sort)
                {
                    case "All":
                        recipes = recipes;
                        break;
                    case "Alcoholic":
                        recipes = recipes.Where(r => r.RecipesCategories.Any(rc => rc.Category.Name == "Alcoholic"));
                        break;
                    case "Non-Alcoholic":
                        recipes = recipes.Where(r => r.RecipesCategories.Any(rc => rc.Category.Name == "Non-Alcoholic"));
                        break;
                }
            }
            List<Recipe> res = recipes.ToList();

            return PartialView("_RecipesPartial", res);
        }


        [HttpPost]
        public async Task<IActionResult> SortPrice(string[] price)
        {
            ViewBag.Ratings = await _ratingService.GetAllAsync();
            IEnumerable<Recipe> queryPrice = await _recipeService.GetAllAsync();

            if (price != null && price.Length > 0)
            {
                if (price.Contains("expensive"))
                    queryPrice = queryPrice.Where(x => x.Price > 15);
                if (price.Contains("middle"))
                    queryPrice = queryPrice.Where(x => x.Price >= 7 && x.Price <= 15);
                if (price.Contains("cheap"))
                    queryPrice = queryPrice.Where(x => x.Price >= 1 && x.Price <= 7);
            }

            var results = queryPrice.ToList();
            return PartialView("_RecipesPartial", results);
        }
        static List<Recipe> RelatedProducts(IQueryable<Recipe> queryable, Recipe recipe, int id)
        {
            List<Recipe> relateds = new();

            recipe.RecipesCategories.ForEach(rc =>
            {
                List<Recipe> related = queryable.
                        Include(r => r.RecipesImages).
                        Include(r => r.RecipesCategories).ThenInclude(p => p.Category).
                       AsEnumerable().
                       Where(r => r.RecipesCategories.Contains(rc, new RecipeCategoryComparer())
                            && r.Id != id && !relateds.Contains(r, new RecipeComparer())).
                            Take(4).
                            ToList();
                relateds.AddRange(related);

            });
            return relateds;
        }

        [HttpPost]
        public async Task<IActionResult> AddComment(int id, Comment comment)
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Login", "Account");
            }
            if (comment.Text is null)
            {
                ModelState.AddModelError("", "Please add text ");
                return View();
            }

            if (User.Identity.IsAuthenticated)
            {
                Recipe recipe = await _recipeService.GetFullDataByIdAsync(id);
                if (recipe == null)
                {
                    return NotFound();
                }

                User user = await _userManager.FindByNameAsync(User.Identity.Name);

                Rating ratingRegistered = new()
                {
                    Point = comment.Rating.Point
                };

                Comment commentRegistered = new()
                {
                    Text = comment.Text,
                    User = user,
                    Recipe = recipe,
                    Rating = ratingRegistered,
                    CreationTime = DateTime.Now
                };

                double rateCount = _context.Ratings.Where(r => r.Comment.RecipeId == id).Count();

                comment.Text = string.Empty;

                if (recipe.PointReyting.HasValue)
                {
                    double currentTotalRating = recipe.PointReyting.Value * rateCount;
                    double newTotalRating = currentTotalRating + comment.Rating.Point;
                    rateCount++;
                    double averageRating = newTotalRating / rateCount;
                    recipe.PointReyting = Math.Min(10.0, averageRating);
                }
                else
                {
                    recipe.PointReyting = Math.Min(10.0, comment.Rating.Point);
                }

                _context.Comments.Add(commentRegistered);
                _context.Recipes.Update(recipe);
                await _context.SaveChangesAsync();
            }

            return RedirectToAction(nameof(Detail), new { id });
        }


        /// <summary>
        /// I hid the viewbags I sent in actions here
        /// </summary>
        private async Task AllViewBagsData()
        {
            ViewBag.Categories = _context.Categories.AsEnumerable();

        }



    }
}

The-Fruity-Mixologist-Back-End-/TheFruityMixologist/Views/Shop/Detail.cshtml
@model Recipe
@{
    ViewData["Title"] = "Detail";
    List<Recipe> related = ViewBag.RelatedProduct;
}
<style>
    .yellow-star {
        color: yellow;
    }

    .gray-star {
        color: gray;
    }
</style>
<main>
    <section id="Detail">
        <div class="container">
            <div class="row">
                <div class="cocktailName">
                    <span> @Model.Name </span>
                </div>
                <div class="imagesAndDesc">
                    <div class="container">
                        <div class="row">
                            <div class="col-lg-6">
                                <div class="mainImage">
                                    <img style="width: 100%; height:100%"
                                         src="~/assets/photos/Recipes/@Model.RecipesImages.FirstOrDefault(ri=>ri.IsMain==true)?.Path" />
                                </div>
                            </div>
                            <div class="col-lg-5">
                                <div class="Falseimage">
                                    <img style="width: 100%; height:100%"
                                         src="~/assets/photos/Recipes/@Model.RecipesImages.FirstOrDefault(ri=>ri.IsMain==false)?.Path" />
                                </div>
                                
                                <span class="price">$@Model.Price</span>
                                <span class="like">
                                    <a class="heartIconn" id="like" data-recipe-id="@Model.Id">
                                        <i class="bi bi-heart likeIcon  @(Model.WishListItems.Any(w => w.User.UserName == User.Identity.Name && w.isLiked == true) ? "d-none" : "")"></i>
                                    </a>
                                    <a class="heartIconn" id="removelike" data-recipe-id="@Model.Id">
                                        <i class="bi bi-heartbreak removelikeIcon   @(Model.WishListItems.Any(w => w.User.UserName == User.Identity.Name && w.isLiked == true) ? "hidden" : "")"></i>
                                    </a>

                                </span>
                                <p class="desc">
                                    @Model.Desc
                                </p>
                              
                                <form asp-controller="Basket" asp-action="AddBasket" asp-route-id="@Model.Id">
                                    <div class="quantity">
                                            <button type="button" style="width: 35px;background-color: white;" class="qtyminus" aria-hidden="true">&minus;</button>
                                            <input type="number" name="count" id="qty" min="1" max="10" step="1" value="1">
                                            <button type="button" style="width: 35px;background-color: white;" class="qtyplus" aria-hidden="true">&plus;</button>
                                    </div>
                                <div class="addtoBasket">
                                    <button type="submit">Add to basket</button>
                                </div>
                                    </form>
                            
                                
                               
                            </div>
                        </div>
                    </div>
                </div>
                <div class="line"></div>
            </div>
        </div>
        <div class="IngredientsandSteps">
            <div class="container">
                <div class="row">
                    <div class="col-lg-4">
                        <div class="Ingredients">
                            <span class="title">Ingredients</span>
                            <ol type="1" start="1" class="Ingredient">
                                @foreach (var ingredients in Model.Ingredients) { 
                                    <li>@ingredients.Ingredients</li>
                                }
                            </ol>
                        </div>
                    </div>
                    <div class="col-lg-8">
                        <div class="Steps">
                            <span class="title">Steps</span>
                            <ol type="1" start="1" class="Steps">
                                @foreach (var steps in Model.Steps)
                                {
                                    <li>@steps.Steps</li>
                                }
                            </ol>
                        </div>
                    </div>
                    <div class="line"></div>
                </div>
            </div>
        </div>

        <div class="Reviews">
            <div class="container">
                <div class="row">
                    <div class="title">Reviews</div>
                    <div class="comments_users">
                        <div class="addComment">
                            @if(User.Identity.IsAuthenticated){
                                <form style="display: flex;" asp-controller="Shop" asp-action="AddComment" asp-route-id="@Model.Id" method="post">
                                    <div class="add-rate">
                                        
                                        <style>
                                            i::active{
                                                color:yellow;
                                            }
                                        </style>
                                        <i class="fa-regular fa-star rate-it" onclick="fillStars(1)" style="cursor:pointer;font-size:20px;">
                                            <input asp-for="RecipeComments.FirstOrDefault(c=>c.RecipeId == Model.Id).Rating.Point" type="radio" value="1" style="display:none" />
                                        </i>
                                        <i class="fa-regular fa-star rate-it" onclick="fillStars(2)" style="cursor:pointer;font-size:20px;">
                                            <input asp-for="RecipeComments.FirstOrDefault(c=>c.RecipeId == Model.Id).Rating.Point" type="radio" value="2" style="display:none" />
                                        </i>
                                        <i class="fa-regular fa-star rate-it" onclick="fillStars(3)" style="cursor:pointer;font-size:20px;">
                                            <input asp-for="RecipeComments.FirstOrDefault(c=>c.RecipeId == Model.Id).Rating.Point" type="radio" value="3" style="display:none" />
                                        </i>
                                        <i class="fa-regular fa-star rate-it" onclick="fillStars(4)" style="cursor:pointer;font-size:20px;">
                                            <input asp-for="RecipeComments.FirstOrDefault(c=>c.RecipeId == Model.Id).Rating.Point" type="radio" value="4" style="display:none" />
                                        </i>
                                        <i class="fa-regular fa-star rate-it" onclick="fillStars(5)" style="cursor:pointer;font-size:20px;">
                                            <input asp-for="RecipeComments.FirstOrDefault(c=>c.RecipeId == Model.Id).Rating.Point" type="radio" value="5" style="display:none" />
                                        </i>

                                    
                                    <input style="width: 300px;" type="text" asp-for="RecipeComments.FirstOrDefault(cm => cm.Recipe.Id == Model.Id).Text" class="form-control" placeholder="Comment" />
                                 
                                        <button type="submit" class="ms-2" >Add Comment</button>
                                </form>
                                <script>
                                    function fillStars(rating) {
                                        const stars = document.querySelectorAll('.rate-it');
                                        stars.forEach((star) => {
                                            star.addEventListener("click", function(){
                                                star.firstElementChild.click()
                                                 star.classList.add("active");
                                             star.style.color = "yellow";
                                            })
                                        });

                                        const form = document.querySelector('form');
                                        const formData = new FormData(form);

                                        fetch(form.action, {
                                            method: form.method,
                                            body: formData
                                        })
                                            .then(response => response.text())
                                            .then(result => {
                                                console.log(result);
                                            })
                                            .catch(error => console.log(error));

                                        stars.forEach((star, i) => {
                                            star.addEventListener("click", function () {
                                                star.firstElementChild.click();
                                                let currentStar = i + 1;
                                                stars.forEach((star, j) => {
                                                    if (currentStar >= j + 1) {
                                                        star.classList.add("active");
                                                        star.style.color = "#FEC006";
                                                    } else {
                                                        star.classList.remove("active");
                                                        star.style.color = "lightgray";
                                                    }
                                                });
                                            })
                                        });
                                    }

                                   
                                </script>
                            




                            }
                        </div>

                        @foreach(var comment in Model.RecipeComments)
                        {
                            <div class="comment_item">
                                <div class="comment_item_user">
                                    <img class="primary-img" style="width:100px;height:100px; object-fit:contain"
                                     src="~/assets/photos/myAccount/@comment.User.Path"
                                     alt="User Image" />   
                                     <div class="rayting" >
                                        @{
                                            double rating = comment.Rating.Point;
                                            }
                                        @{
                                            for (int i = 1; i <= 5; i++){
                                                if (i <= rating)
                                                {
                                                            <span class="yellow-star">&#9733;</span>
                                           }
                                           else{
                                                           <span class="gray-star"></span>
                                           }
                                       }
                                    }

                                     </div>
                                    <span class="user_name">@comment.User.UserName</span>
                                    <span class="date">@comment.CreationTime</span>
                                </div>
                                <div class="comment_item_content">
                                    <p>
                                       @comment.Text
                                    </p>
                                </div>
                            </div>

                        }
                        

                    </div>
                    <div class="line"></div>
                </div>
            </div>
        </div>
    </section>

    <section id="RelatedProducts">
        <div class="container">
            <div class="row">
                <div class="title">More products you may like</div>
                <div class="products">
                    <div class="row">
                        @await Html.PartialAsync("_RelatedRecipes", related)
                    </div>
                </div>
            </div>
        </div>
    </section>
</main>


@section Scripts{
    <script src="~/assets/js/detail.js"></script>
}

The-Fruity-Mixologist-Back-End-/TheFruityMixologist/Views/Shop/Index.cshtml
@using TheFruityMixologist.Entities
@model List<Recipe>
@{
    ViewData["Title"] = "Index";
    List<Recipe> recipes = ViewBag.Recipes;
    string filter = ViewBag.Filters;
    int selectedPage = ViewBag.SelectedPage;
    decimal totalPage = ViewBag.TotalPage;
}

 <main>
      <div class="container">
        <div class="row">
          <section id="Recipes">
            <div class="container">
              <div class="row">
                <div class="col-lg-3 refineYourSearch"
                  style="border-right: 1px solid #707070"
                >
                  <span class="RefineYour">Refine your search</span>
                            <form action="#">
                             
                                <p>Price</p>

                                <input type="checkbox" id="price110" name="price" value="expensive" onchange="filterPrice()" />
                                <label class="checkbox" for="price110">
                                    $ 15+
                                </label><br />

                                <input type="checkbox" id="price3050" name="price" value="middle" onchange="filterPrice()" />
                                <label class="checkbox" for="price3050">
                                    $7 - $15
                                </label><br />

                                <input type="checkbox" id="price5070" name="price" value="cheap" onchange="filterPrice()" />
                                <label class="checkbox" for="price5070">
                                    $1 - $7
                                </label><br />


                                <script>
                                    function filterPrice() {
                                        const selectedPrices = Array.from(document.querySelectorAll('input[name="price"]:checked')).map(checkbox => checkbox.value);

                                        const formData = new FormData();
                                        selectedPrices.forEach(price => {
                                            formData.append('price', price);
                                        });

                                        fetch('/shop/SortPrice', {
                                            method: 'POST',
                                            body: formData
                                        })
                                            .then(response => response.text())
                                            .then(result => {
                                                document.getElementById('recipesResult').innerHTML = result;
                                            })
                                            .catch(error => console.log(error));
                                    }
                                </script>
                            </form>
                </div>
                <div class="col-lg-9">
                  <div class="row">
                    <div class="categorys">
                      <div class="col-lg-12">
                        <nav>
                         <ul>
                                                <li><a asp-controller="shop" asp-action="Sorts" name="sort" value="All">All</a></li>
                                                <li><a asp-controller="shop" asp-action="Sorts" name="sort" value="Alcoholic">Alcoholic</a></li>
                                                <li><a asp-controller="shop" asp-action="Sorts" name="sort" value="Non-Alcoholic">Non-Alcoholic</a></li>
                                                <li><a asp-controller="CreateCocktail" asp-action="Index">Cook it yourself</a></li>
            </ul>
            <script>
                                                                const sortLinks = document.querySelectorAll('a[name="sort"]');

                                                sortLinks.forEach(link => {
                                                    link.addEventListener('click', (event) => {
                                                        event.preventDefault();
                                                        const selectedSort = link.getAttribute('value');

                                                        fetch(`/shop/Sorts?sort=${selectedSort}`, {
                                                            method: 'POST'
                                                        })
                                                            .then(response => response.text())
                                                            .then(result => {
                                                                document.getElementById("recipesResult").innerHTML = result;
                                                            })
                                                            .catch(error => console.log(error));
                                                    });
                                                });
            </script>
                        </nav>
                      </div>
                    </div>
                    <div class="products" >
                                    <div class="container">
                                        <div class="row" id="recipesResult">
                                            @await Html.PartialAsync("_RecipesPartial", recipes)
                                        </div>
                                    </div>
                                    <div class="pagination d-flex justify-content-center mt-5"
                                        <nav class="pagination-outer" aria-label="Page navigation">
                                            <ul class="pagination">

                                                @if (selectedPage > 1)
                                                {
                                                    <li class="page-item">
                                                        <a asp-action="index" asp-route-page="@(selectedPage-1)" asp-route-fitler="@ViewBag.Filters" class="page-link" aria-label="Previous">
                                                            <span aria-hidden="true">«</span>
                                                        </a>
                                                    </li>
                                                }

                                                @{
                                                    int startPage = (selectedPage == 1 || totalPage <= 3) ? 1 : selectedPage < totalPage ? selectedPage - 1 : selectedPage - 2;
                                                    int endPage = totalPage > 2 ? startPage + 2 : (int)totalPage;
                                                }

                                                @for (int i = startPage; i <= endPage; i++)
                                                {
                                                    <li class="page-item @(i==selectedPage?"active":"")"><a class="page-link" asp-action="index" asp-route-page="@i" asp-route-fitler="@ViewBag.Filters">@i</a></li>

                                                }

                                                @if (selectedPage < totalPage)
                                                {

                                                    <li class="page-item">
                                                        <a asp-action="index" asp-route-page="@(selectedPage+1)" asp-route-search="@ViewBag.CurrentSearch" asp-route-regionIdId="@ViewBag.CurrentRegionId" asp-route-typeId="@ViewBag.CurrentTypeId" asp-route-variatyId="@ViewBag.CurrentVariatyId" class="page-link" aria-label="Next">
                                                            <span aria-hidden="true">»</span>
                                                        </a>
                                                    </li>
                                                }

                                            </ul>
                                        </nav>
                                    </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>
        </div>
      </div>
    </main>